// Source: the three completed AE311 team reports supplied by the portfolio owner.
export const aerodynamics = [
  {
    slug: 'weather-balloon', title: 'Modeling balloon ascent to compare hydrogen and helium for a 35 km mission', name: 'Modeling balloon ascent to compare hydrogen and helium for a 35 km mission',
    codeLink: ['View archived ascent-model code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae311/weather-balloon'],
    category: 'analysis', type: 'Atmospheric flight modeling', status: 'Completed modeling study', art: 'plot', cardFit: 'contain',
    context: 'AE311 · Technical lead · Three-person team', roleLabel: 'My contribution',
    role: 'Technical lead: mathematical model, Python simulation, plots, and solution documentation',
    description: 'Built a Python model connecting atmospheric conditions, buoyancy, balloon expansion, and burst limits to a gas-cost decision for a 3 kg payload and 35 km target.',
    tags: ['Python', 'Numerical integration', 'Buoyancy', 'Trade studies'],
    lead: 'As technical lead, I modeled how much lifting gas a balloon would need to carry a 3 kg payload to 35 km before bursting. I connected atmospheric conditions, latex-envelope expansion, and vertical motion in a Python simulation, then used repeated runs to support the team’s hydrogen-versus-helium gas-cost recommendation.',
    outcome: 'Report selected 0.43 kg hydrogen as the lower gas-cost case',
    image: 'weather-balloon-force-diagram.png', imageWidth: 813, imageHeight: 487,
    caption: 'The report’s free-body diagram for an ascending balloon: buoyancy opposes the combined weight and drag. This force balance forms the starting point for the numerical model. Figure 3, page 4.',
    evidenceNote: 'AE311 Project 1 by Jackson M. Rees, Benjamin R. McDonald, and Maxwell G. Lutter. The report identifies Maxwell as technical lead on pages 1 and 19–20.',
    sections: [
      {title: 'Make the cost question physically meaningful', paragraphs: ['The team’s mission requirement was to reach at least 35 km with a 3 kg payload before the balloon burst. Gas species and initial gas mass were the variables we could change. A simple lift calculation at launch would not answer the question: the atmosphere changes throughout ascent, and the balloon expands as external pressure falls.', 'I was responsible for simplifying the problem, developing and documenting the mathematical model, implementing the simulation, and producing plots. We represented the envelope as a spherical natural-latex shell so that its volume, mass, stress, and motion could be connected within an academic model.']},
      {title: 'Connect the atmosphere, envelope, and motion', paragraphs: ['I derived buoyancy by integrating pressure over the balloon surface, then combined it with gravity and drag to calculate vertical acceleration. Piecewise atmosphere functions supplied temperature, pressure, and density at the current altitude; ideal-gas and latex-envelope relations supplied the changing balloon size.', 'The implementation had to update these quantities together rather than treat them as independent inputs. The radius calculation selected a physical positive root, envelope expansion changed the geometry, and a stress comparison determined when the simulated ascent stopped. Euler integration advanced velocity and altitude through time.']},
      {title: 'Turn repeated simulations into a design comparison', paragraphs: ['The program increased gas mass in 0.01 kg steps until the altitude criterion was met, recording trial results in a CSV table. Trajectory, velocity, diameter, and failure-margin plots made the calculation inspectable beyond a single final answer. NumPy, Matplotlib, and pandas connected the numerical work to the report’s gas comparison.', 'This work demonstrates the full path from a physical requirement to equations, a computational procedure, and a documented engineering recommendation. The plots explain how a changing environment affects the system, while the trial table connects those calculations to the gas-mass decision.'], figure: {image: 'weather-balloon-trajectory.png', imageWidth: 976, imageHeight: 728, caption: 'The submitted model’s altitude-versus-time trajectory. It illustrates the simulation output used in the trade study, rather than measured balloon performance. Figure 11, page 15.'}},
      {title: 'Recommendation and the confidence it supports', callout: 'The report selected 0.43 kg of hydrogen over 0.95 kg of helium as its lower gas-cost case.', paragraphs: ['Both selected cases exceeded the altitude target in the submitted calculations. The conclusion was a gas-cost recommendation under the report’s historical price assumptions, rather than a comparison of complete launch costs.', 'The study’s value is the coupled modeling and comparison process. Its spherical-envelope assumption, constant drag coefficient, omitted wind and payload drag, and simplified failure treatment limit predictive confidence. The submitted implementation was not independently validated, so the selected masses remain report findings rather than a flight-qualified configuration.']}
    ],
    resources: [['Archived hydrogen-model code & version notes', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae311/weather-balloon', 'GitHub code'], ['Available development notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae311/weather-balloon/311CodeProject1.ipynb', 'Jupyter'], ['Full project report · 28 pages', '../reports/weather-balloon.pdf', 'PDF']]
  },
  {
    slug: 'airfoil-panel-study', title: 'Comparing glider airfoil shapes with panel methods and XFOIL', name: 'Comparing glider airfoil shapes with panel methods and XFOIL',
    codeLink: ['View recovered panel-method code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae311/airfoil-panel'],
    category: 'analysis', type: 'Aerodynamics & design research', status: 'Completed team study', art: 'plot', cardFit: 'contain',
    context: 'AE311 · Real-world problem lead · Three-person team', roleLabel: 'My contribution',
    role: 'Glider design research, tradeoff framing, airfoil-selection context, and report coauthorship',
    description: 'Connected glider design research to a 16-case comparison of camber, thickness, and angle of attack, using panel-method lift and pressure distributions with an XFOIL comparison.',
    tags: ['Design research', 'Panel methods', 'NACA airfoils', 'XFOIL'],
    lead: 'A glider’s airfoil must be chosen in the context of the whole wing and its flight conditions. I led the design research that narrowed this broad question into a comparison of four NACA sections. The team then used a Python panel method to show how camber, thickness, and angle of attack changed lift and pressure across sixteen cases.',
    outcome: 'NACA 6412 had the highest modeled lift in the 16 tested cases',
    image: 'airfoil-panel-streamlines.png', imageWidth: 610, imageHeight: 245,
    caption: 'Simulated streamlines around the NACA 0006 section from the team’s panel-method analysis. The image shows the modeled flow around the airfoil; it is not a wind-tunnel observation. Figure 15, page 19.',
    evidenceNote: 'AE311 Project 2 by Benjamin R. McDonald, Jackson M. Rees, and Maxwell G. Lutter. Maxwell’s research role is documented on pages 1, 25, and 28.',
    sections: [
      {title: 'Choose a question the analysis can answer', paragraphs: ['My research surveyed glider development and modern design choices, including airfoil shape, aspect ratio, winglets, and wing configuration. The challenge was to connect these interacting choices to a focused investigation the team could complete with potential-flow methods.', 'We concentrated on airfoil geometry. NACA 0006, 0012, 6406, and 6412 supplied thin/thick and symmetric/cambered pairs; testing each at −3°, 0°, 3°, and 6° created sixteen cases. This gave the numerical work a design purpose and a comparison structure, rather than an arbitrary set of airfoils.']},
      {title: 'Compare a computed flow field with a reference', paragraphs: ['The team’s combined source/vortex panel method enforced an impermeable surface and the Kutta condition. Surface pressure and circulation provided routes to lift, while geometry, streamline, and pressure plots helped explain the flow field. Pressure distributions were compared with XFOIL as a reference.', 'Jackson Rees was the technical lead and implemented the Python solver, adapted from JoshTheEngineer as credited in the report. I led the design research and helped connect practical glider considerations to the team’s analysis and report.'], figure: {image: 'airfoil-panel-xfoil-comparison.png', imageWidth: 1447, imageHeight: 1091, caption: 'Pressure distributions for NACA 6406: panel-method points compared with XFOIL reference curves. This is the report’s principal method-comparison figure. Figure 20, page 22.'}},
      {title: 'Explain what the geometry changed', callout: 'Cambered sections produced positive lift at zero incidence; NACA 6412 had the highest lift coefficient in the tested cases.', paragraphs: ['The symmetric sections were approximately at zero lift at zero incidence, while the cambered sections produced positive lift. NACA 6412 returned a reported lift coefficient of about 0.729 at zero degrees. The pressure plots provided a visual explanation for these differences, connecting the tabulated coefficients back to the airfoil shape.']},
      {title: 'Carry the result back to the design decision', paragraphs: ['The research and analysis together support an informed preliminary comparison of airfoil behavior. They also make clear which important glider questions remain unanswered: the steady, inviscid, attached two-dimensional model cannot predict stall, viscous drag, or complete-aircraft glide performance.', 'My contribution demonstrates technical research and problem framing: identifying relevant design variables, connecting a broad system goal to an achievable analysis, and explaining the limits of the evidence. The report’s highest modeled lift coefficient is useful comparison evidence, but is not enough on its own to select the best overall glider.']}
    ],
    resources: [['Recovered team code, attribution & dependency notes', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae311/airfoil-panel', 'GitHub code'], ['Python recovered from the notebook export', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae311/airfoil-panel/panel_method_export.py', 'Python'], ['Full project report · 31 pages', '../reports/airfoil-panel-study.pdf', 'PDF']]
  },
  {
    slug: 'finite-wing-study', title: 'Selecting a tapered wing using lifting-line design trades', name: 'Selecting a tapered wing using lifting-line design trades',
    category: 'analysis', type: 'Aerodynamic design trades', status: 'Preliminary design study', art: 'plot', cardFit: 'contain',
    context: 'AE311 · Team lead · Three-person team', roleLabel: 'My contribution',
    role: 'Team coordination, investigation scope, plot digitization, and technical documentation',
    description: 'Led a three-person study connecting span limits and manufacturing constraints to a preliminary tapered-wing recommendation, using planform, aspect-ratio, and twist comparisons.',
    tags: ['Team leadership', 'Lifting-line theory', 'Python / Jupyter', 'Design trades'],
    lead: 'Our hypothetical recreational aircraft needed an efficient wing that could fit within a 12 m span limit and avoid the manufacturing difficulty of an elliptical planform. I led the three-person team that connected those constraints to a lifting-line trade study. Comparing planform, aspect ratio, and twist led to a preliminary recommendation for an 11 m tapered wing.',
    outcome: 'Recommended 11 m span, 0.4 taper ratio, and no geometric twist',
    image: 'wing-planform-drag-polars.png', imageWidth: 1458, imageHeight: 1161,
    caption: 'Modeled lift and induced drag for four planforms at 11 m span. These configurations also differ in aspect ratio, so this comparison does not isolate planform alone. Figure 13, page 23.',
    evidenceNote: 'AE311 Project 3 by Maxwell G. Lutter, Benjamin R. McDonald, and Jackson M. Rees. Maxwell’s team-lead and support contributions are documented on pages 1, 27, and 29.',
    sections: [
      {title: 'Balance aerodynamic benefit with a buildable shape', paragraphs: ['The scenario imposed a maximum 12 m wingspan and a budget that excluded elliptical-wing manufacture. The task was therefore to compare simpler planforms and identify geometry that approached the aerodynamic reference while remaining compatible with those constraints.', 'I coordinated the investigation’s scope, schedule, and division of work. Benjamin McDonald developed the computational model as technical lead, while Jackson Rees led the real-world research. I supported plot digitization, mathematical and reference formatting, report preparation, and discussions connecting the two investigations.']},
      {title: 'Use comparisons to support each design choice', paragraphs: ['The team used Prandtl lifting-line theory with Fourier-series circulation to calculate lift, induced drag, and span efficiency. The ideal elliptical case supplied a useful check: its reported span efficiency was 1.0 and its higher Fourier coefficients were effectively zero.', 'The study then swept aspect ratio, compared elliptical, rectangular, and two tapered planforms at 11 m span, and tested ±2° twist on a rectangular wing. The fixed-span comparison represented feasible configurations; because their areas and aspect ratios also differed, it did not isolate planform shape as the only cause of the performance differences.'], figure: {image: 'wing-twist-drag-polars.png', imageWidth: 1458, imageHeight: 1081, caption: 'The report’s rectangular-wing twist comparison. The small modeled benefit of washout was weighed against added manufacturing complexity. Figure 14, page 25.'}},
      {title: 'Keep the investigation focused enough to finish', paragraphs: ['The team’s ambitions initially extended beyond the time available near the end of the semester. The report identifies scope control as a practical obstacle: core objectives had to take priority over supplemental investigation.', 'My role shifted from guiding topic selection to reducing the team’s documentation and analysis-support workload, allowing the technical and research leads to concentrate on their investigations. The completed report joined the physical explanation, numerical comparisons, and manufacturing constraints into one design recommendation.']},
      {title: 'Make a recommendation with explicit assumptions', callout: '11 m span, 1 m root chord, 0.4 m tip chord, and no geometric twist.', paragraphs: ['The report favored a high aspect ratio and 0.4 taper ratio to approach the elliptical reference’s induced-drag performance with simpler manufacture. Choosing 11 m left clearance within the 12 m span limit. The small modeled benefit of washout was judged insufficient to justify its added manufacturing difficulty.', 'The no-twist recommendation assumes that the rectangular-wing trend carries over to the proposed tapered wing. It is a preliminary aerodynamic choice: structural sizing, viscous effects, stall, and whole-aircraft behavior were outside the small-angle, attached-flow model. My contribution provides evidence of technical coordination and synthesis—turning a team’s research and numerical results into a clear, bounded design decision.']}
    ],
    resources: [['Full project report · 30 pages', '../reports/finite-wing-study.pdf', 'PDF']]
  }
];
