// Sources: the recovered DP1 report and CMGDemo-Team17.ipynb with its original saved outputs.
export const catbot = {
  slug: 'cat-catching-robot', title: 'Balancing a wheeled robot through a cat-catching impact with state feedback', name: 'Balancing a wheeled robot through a cat-catching impact with state feedback',
  category: 'controls', type: 'Robot feedback control', status: 'Simulated controller', art: 'plot', cardFit: 'contain',
  context: 'AE353 DP1 · Maxwell Lutter & Luke Phan', roleLabel: 'Team contribution', role: 'Controller-design, simulation, and report work co-authored with Luke Phan',
  description: 'With Luke Phan, designed wheel-torque feedback to balance a robot before and after catching a falling cat in simulation. Checked candidate gains for local stability, implemented torque limits, and examined the residual offsets after impact.',
  tags: ['State feedback', 'Eigenvalue analysis', 'Torque limits', 'Python / SciPy'],
  lead: 'A wheeled robot had to balance upright, reach the catching location, and remain stable after a falling cat struck its basket. With Luke Phan, I developed a four-state feedback design and tested it in the supplied course simulator. A saved run caught and held the cat; the response plots also revealed residual position and pitch offsets after the impact, making the model’s limits part of the result.',
  outcome: 'One documented successful catch; post-impact equilibrium offsets identified',
  codeLink: ['View team controller code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/catbot'],
  image: 'catbot-simulation-snapshot.png', imageWidth: 685, imageHeight: 395,
  caption: 'Original saved simulation snapshot after the team’s 20-second run, showing the wheeled basket on its platform. The notebook records a successful catch for this demonstration.',
  evidenceNote: 'DP1: Control System Design for a Cat-Catching Robot by Maxwell Lutter and Luke Phan, recovered from the Overleaf archive and checked against CMGDemo-Team17.ipynb. The report and notebook do not divide individual functions. Tim Bretl, Wayne Chang, and the course staff supplied the equations and simulation infrastructure.',
  sections: [
    {title: 'Choose feedback around the upright equilibrium', paragraphs: ['The model used body pitch, wheel position, and their rates, with wheel torque as the input. The team linearized around an upright, stationary robot and generated candidate feedback gains, screening them by the closed-loop eigenvalues.', 'A matrix-exponential state response checked how the selected gain recovered from a small perturbation. The controller then mapped the measured state to a torque command clipped to ±5 N·m, carrying the local feedback design into the nonlinear simulation.']},
    {title: 'Work around unreliable automatic screening', paragraphs: ['The notebook records different behavior when the simulator display was disabled, which undermined an intended automatic search across gains and repeated trials. Enabling the display made screening slow, so the team selected a demonstration gain through manual testing.', 'The final documented experiment ran for 20 seconds from randomized initial conditions, with the cat launched after a short random delay. Success meant catching and holding the cat for the rest of the run. This is a worked demonstration rather than a measured robustness percentage.']},
    {title: 'Read the impact response, not just the catch flag', paragraphs: ['The saved notebook reports a successful catch. The state histories show the initial recovery, a sharp response when the cat hits the basket, and subsequent settling. The robot did not return completely to the platform center or to a perfectly upright pitch.', 'The report proposes that the caught cat’s added mass changes the system dynamics, shifting the behavior away from the equilibrium used to design the gain. That explanation is a hypothesis consistent with the observed response, not a tested payload-adaptive controller.'], figure: {image: 'catbot-state-response.png', imageWidth: 1400, imageHeight: 934, caption: 'Wheel position and velocity, pitch, and pitch rate during the saved 20-second demonstration. The impact near six seconds is followed by settling with nonzero position and pitch offsets.'}},
    {title: 'What the work demonstrates', paragraphs: ['The project connects linearization, eigenvalue-based gain selection, torque-limited implementation, and interpretation of a nonlinear impact response. It also shows why a locally stable nominal model and a successful event do not establish robustness to changed dynamics.', 'Luke Phan and I share credit for the controller study. The linked notebook contains the modeling, gain search, implementation, saved catch result, and response analysis; course-provided physics and visualization remain credited separately.']}
  ],
  resources: [['Controller code, course setup & team credits', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/catbot', 'GitHub code'], ['Archived team notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/catbot/CMGDemo-Team17.ipynb', 'Jupyter'], ['Saved robot state histories', '../assets/catbot-state-response.png', 'Notebook figure']]
};
