// Report-grounded case studies. Source-version details remain in the linked code READMEs.
export const controls = [
  {
    slug: 'flying-wing-control', title: 'Landing an unpowered flying wing with an LQR elevon controller', name: 'Landing an unpowered flying wing with an LQR elevon controller',
    category: 'controls', type: 'Flight dynamics & control', status: 'Evaluated in simulation', art: 'plot', cardFit: 'contain',
    context: 'AE353 · Two-person team project', roleLabel: 'Team contribution',
    role: 'Controller modeling, design, implementation, and evaluation reported jointly with Navid Navidzadeh',
    description: 'With Navid Navidzadeh, turned nonlinear aircraft dynamics into an elevon-feedback landing controller. Tuned control weights and used randomized approaches and failure analysis to assess the limits of the local linear model.',
    tags: ['LQR', 'Aircraft trim', 'State-space modeling', 'Python / SymPy'],
    lead: 'An unpowered flying wing has to reach the runway using only its two elevons. With Navid Navidzadeh, I worked from the supplied nonlinear dynamics to find a feasible glide equilibrium, build an LQR controller, and test whether it could land reliably across varying initial conditions. The resulting 87.3% success rate exceeded the project requirement; studying the misses explained where the design stopped working.',
    outcome: '87.3% landing success across 4,000 simulated trials',
    codeLink: ['View controller code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/flying-wing'],
    image: 'flying-wing-trajectories.png', imageWidth: 1045, imageHeight: 843,
    caption: 'Vertical and lateral approach paths for 20 successful landings in green and 10 failed landings in red. The dotted outline marks the runway. Report Figure 1.',
    evidenceNote: 'AE353 DP2 report by Maxwell Lutter and Navid Navidzadeh, checked against the project notebooks. Controller work is reported jointly; the report does not divide individual code authorship. Tim Bretl, Wayne Chang, and the course staff supplied the aircraft dynamics and simulation framework.',
    sections: [
      {title: 'Find an equilibrium that an unpowered aircraft can sustain', paragraphs: ['The first design obstacle was that a gliding aircraft must keep moving and descending. Requiring every position coordinate to remain constant would make the trim problem inappropriate for unpowered flight. Our team therefore omitted forward and vertical position from the ten-state trim model while retaining the variables that govern the aircraft dynamics.', 'A numerical least-squares search found an equilibrium with elevon deflections inside the permitted range. Jacobians at that operating point produced the linear model; a full-rank controllability check established that the two elevon inputs could influence all ten modeled states.']},
      {title: 'Balance attitude correction against elevon motion', paragraphs: ['We computed the LQR feedback gain from state and input penalties, then adjusted those weights in simulation. Larger attitude penalties emphasized pitch and roll correction, while larger input penalties produced smoother, slower elevon responses. Closed-loop eigenvalues checked local stability before the controller was evaluated in the nonlinear simulator.', 'Tuning was an implementation bottleneck: simulations were expensive, and small trial sets produced highly variable landing percentages. Repeated testing was needed to judge a weight change by landing outcomes rather than by one visually convincing approach.']},
      {title: 'Measure success and explain the misses', callout: '87.3% successful landings over 4,000 randomized trials exceeded the greater-than-85% requirement.', paragraphs: ['The evaluation began 150 m before and 15 m above the runway, with randomized initial airspeeds and small air disturbances. The controller issued right and left elevon commands throughout each approach, and the trial loop classified the landing and recorded position and attitude histories.', 'Successful approaches damped attitude oscillations and reached the runway. Failed paths commonly undershot or drifted laterally; their initial-attitude distributions implicated larger yaw and pitch offsets. The report also identifies trim selection and the physical limits of unpowered flight as possible contributors, rather than assigning every failure to a proven single cause.'], figure: {image: 'flying-wing-failure-attitudes.png', caption: 'Initial yaw, pitch, and roll distributions for failed landings. The report identifies large yaw and pitch offsets as an important weakness of the local controller.'}},
      {title: 'What the work demonstrates', paragraphs: ['This study connects aircraft modeling to an implemented control law and a quantitative acceptance test. The useful result is both the landing percentage and the analysis that bounds it: local linear stability did not guarantee recovery from every randomized starting attitude.', 'The linked team notebooks expose the trim search, symbolic linearization, Riccati-equation solution, Controller class, and trial analysis. Together with the report, they show experience making a workable feedback design, tuning it against a task-level requirement, and using failed runs to assess its operating limits.']}
    ],
    resources: [['Controller notebooks, setup & team credits', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/flying-wing', 'GitHub code'], ['Controller-design notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/flying-wing/DP2_Team33.ipynb', 'Jupyter'], ['Notebook with saved 4,000-trial result', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/flying-wing/ZagiDemo-template.ipynb', 'Jupyter'], ['Full project report · 6 pages', '../reports/flying-wing-control.pdf', 'PDF']]
  },
  {
    slug: 'spacecraft-attitude', title: 'Stabilizing a spacecraft hatch with reaction wheels and a star-based observer', name: 'Stabilizing a spacecraft hatch with reaction wheels and a star-based observer',
    category: 'controls', type: 'Spacecraft control', status: 'Evaluated in simulation', art: 'plot', cardFit: 'contain',
    context: 'AE353 · Two-person team project', roleLabel: 'Team contribution',
    role: 'Controller and observer modeling, implementation, and testing reported jointly with Adrian Huang',
    description: 'With Adrian Huang, combined reaction-wheel feedback and noisy star measurements to align a spacecraft hatch for astronaut entry. Separate estimation and mission tests revealed the limits of the integrated design.',
    tags: ['LQR', 'State estimation', 'Reaction wheels', 'PyBullet'],
    lead: 'The spacecraft needed to keep its hatch aligned for a returning astronaut while debris disturbed its attitude and noise obscured star measurements. With Adrian Huang, I developed an LQR reaction-wheel controller and a dual-LQR observer. Testing the complete system exposed a useful engineering distinction: the illustrated observer trials met the accuracy threshold, but mission success remained below the required level.',
    outcome: '64% mission success; illustrated observer trials below the 3.5° error limit',
    codeLink: ['View controller & observer code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/spacecraft'],
    image: 'spacecraft-simulation-snapshot.png', imageWidth: 676, imageHeight: 513,
    caption: 'Original saved PyBullet scene from the team notebook: the spacecraft, hatch, returning astronaut, and surrounding objects. This illustrates the simulated task; the mission and estimation results are evaluated separately below.',
    evidenceNote: 'AE353 DP3 report by Maxwell Lutter and Adrian Huang, checked against SpacecraftDemo.ipynb. Student contributions are reported jointly. Tim Bretl, Wayne Chang, and the course staff supplied the dynamics, design utilities, and simulation framework.',
    sections: [
      {title: 'Distribute control authority and recover the hidden state', paragraphs: ['Our team chose a tetrahedral arrangement of four reaction wheels to provide approximately balanced torque authority in three dimensions and distribute the load among actuators. A six-state attitude-and-angular-rate model described the local spacecraft motion.', 'Seven observed stars supplied fourteen image-plane coordinates, rather than direct measurements of all six states. Linearizing that sensor model and checking rank-six controllability and observability established the basis for feedback and an observer that reconstructs attitude and angular rate from noisy measurements.']},
      {title: 'Make the observer and controller work together', paragraphs: ['LQR state and torque weights traded tight attitude regulation against actuator effort. The dual-LQR observer added a second tuning problem: correct disturbance-driven changes quickly enough without following measurement noise too aggressively.', 'The team first selected a controller using the true state, then added the observer and sensor noise. The report gives roughly 85% success for the best controller-only setting, but that performance did not carry through to the integrated system. This made the interaction between estimation, disturbances, and available wheel torque the central obstacle.']},
      {title: 'Evaluate estimation and mission completion separately', callout: 'The report records 64% successful astronaut entries in 200 simulations, below the 80% mission target.', paragraphs: ['Mission trials lasted 60 seconds and included randomized initial conditions, sensor noise, and debris disturbances. A separate observer criterion used the 95th percentile of attitude-error magnitude over 20–60 seconds, with a 3.5° limit.', 'All 25 trials illustrated in the report’s observer plot lie below that limit. The report concludes that its observer criterion was met; the figure does not establish the observer pass rate across the full 200-trial mission set. The mission shortfall remains visible alongside the favorable estimation result.'], figure: {image: 'spacecraft-observer-error.png', caption: 'The 25 illustrated observer trials remain below the 3.5° limit for 95th-percentile attitude-estimation error. Their relationship to the report’s 200 mission trials is not specified.'}},
      {title: 'Use the shortfall to guide the next design decision', paragraphs: ['The report identifies limited reaction-wheel torque, large disturbances, and the difficulty of separating disturbance response from sensor noise as constraints on recovery. It proposes more systematic selection of controller and observer weights instead of relying on trial and error.', 'This project shows experience integrating an observer with feedback, defining different acceptance measures for estimation and mission behavior, and diagnosing a design that missed its system-level target. The linked notebook contains the wheel layout, state and sensor linearization, gain calculations, state-estimate update, wheel-torque commands, and trial analysis.']}
    ],
    resources: [['Controller and observer code, setup & team credits', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/spacecraft', 'GitHub code'], ['Archived spacecraft notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/spacecraft/SpacecraftDemo.ipynb', 'Jupyter'], ['Full project report · 7 pages', '../reports/spacecraft-attitude.pdf', 'PDF']]
  },
  {
    slug: 'reentry-thermal-model', title: 'Verifying a layered heat-shield model for reentry conduction', name: 'Verifying a layered heat-shield model for reentry conduction',
    category: 'analysis', type: 'Computational heat transfer', status: 'Completed team study', art: 'plot', cardFit: 'contain',
    context: 'AE370 · Five-person team project', roleLabel: 'My contribution',
    role: 'Verification and implementation writing, derivation-to-code checks, result interpretation, plotting, and report editing',
    description: 'Checked and explained the numerical evidence behind a team model of reentry heating through a layered heat shield. Connected the implementation to manufactured-solution convergence and an analytical benchmark, then interpreted the tradeoff between surface heating and heat penetration.',
    tags: ['Finite volumes', 'Crank–Nicolson', 'Manufactured solutions', 'Verification'],
    lead: 'Before interpreting a heat-shield temperature prediction, the team needed evidence that the conduction solver behaved correctly. I helped connect the model’s derivations, code, verification plots, and report explanations. The strongest evidence was near-second-order convergence in space and time and agreement with a separate analytical sphere solution; those checks supported an idealized material-sensitivity study.',
    outcome: 'Near-second-order convergence; 0.0161 K maximum benchmark discrepancy',
    codeLink: ['View team solver & verification code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae370/reentry-thermal'],
    image: 'tps-spatial-convergence.png', imageWidth: 578, imageHeight: 459,
    caption: 'The manufactured-solution test reduces temperature error by approximately a factor of four when radial grid spacing is halved, demonstrating the expected second-order spatial behavior. Report Figure 3.',
    evidenceNote: 'AE370 report by Jeremy Zang, Landon Lopez, Danfeng Ye, Max Lutter, and Kenny Carter. The contribution section credits Danfeng with the solver, verification-suite implementation, parameter sweeps, and run scripts; Maxwell’s work centered on checking, interpreting, plotting, and documenting the technical evidence.',
    sections: [
      {title: 'Connect a heating pulse to heat penetration', paragraphs: ['The project asked how thermal-protection material properties affect surface heating and the delayed response at the shield’s back face. A reduced-order reentry trajectory and Sutton–Graves correlation supplied the imposed surface heat flux; radial conduction carried that heat through a spherical outer layer and inner structure.', 'The team used conservative finite volumes on spherical shells, harmonic interface conductivity, Crank–Nicolson time integration, and a tridiagonal solve. These choices preserve the shell heat balance, handle jumps in material properties, and make repeated transient calculations practical.']},
      {title: 'Compare quantities that mean the same thing', callout: 'Observed convergence orders were 1.987–1.999 in space and 1.932–1.995 in time.', paragraphs: ['Manufactured solutions provided a known temperature field and forcing against which the numerical error could be measured. Refining space and time separately checked that the implementation produced its expected order of accuracy, instead of only producing a plausible-looking temperature curve.', 'The analytical cross-check required another important detail: finite-volume unknowns are shell averages. The team therefore averaged the analytical solution over the same cells before comparing it with the numerical result. For a homogeneous sphere under constant inward heat flux, the reported 960-cell, 0.01 s test had a maximum discrepancy of 0.0161 K.'], figure: {image: 'tps-analytical-check.png', caption: 'Numerical shell averages and cell-averaged analytical temperatures at 10 seconds for a homogeneous sphere. The 0.0161 K maximum discrepancy applies to this benchmark, not to reentry prediction accuracy.'}},
      {title: 'Choose resolution around the engineering output', paragraphs: ['Verification established the method’s numerical behavior; a separate sensitivity study then selected practical production settings. The shield’s back-face peak was prioritized because the steep surface gradient was more sensitive to the grid.', 'The reported spatial choice was 25,600 radial cells, the smallest tested grid whose back-face peak differed by less than 1% from the 51,200-cell reference. Choosing a multiple of 40 also aligned the 5 mm material layer with a grid face. Separate sweeps selected a 0.5 s conduction step and 0.05 s trajectory-forcing step. These criteria apply to their individual comparison studies and do not imply that every temperature history is accurate to one common tolerance.']},
      {title: 'Interpret the material tradeoff within the model’s limits', paragraphs: ['The report concludes that lower conductivity improves back-face insulation at the cost of a hotter surface, while higher conductivity transports heat inward sooner. Greater volumetric heat capacity generally lowers temperature peaks and delays back-face heating.', 'The model prescribes the heating and uses constant material properties without ablation or radiative cooling. These results support numerical verification and qualitative sensitivity comparisons; the absolute temperatures are not flight predictions or evidence that a material has been qualified.']},
      {title: 'My contribution: make the technical evidence defensible', paragraphs: ['I wrote portions of the implementation and numerical-reliability sections, checked methods and derivations against the code and course material, helped interpret verification results and work through inconsistencies, and contributed plots, report structure, and editing.', 'This work demonstrates numerical-method literacy and technical review: understanding what a benchmark actually checks, comparing cell averages consistently, distinguishing verification from physical validation, and explaining which design conclusions the evidence supports. Danfeng Ye implemented the solver and test suite; the contribution statement preserves that distinction.']}
    ],
    resources: [['Team implementation, verification & contribution notes', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae370/reentry-thermal', 'GitHub code'], ['Archived verification notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae370/reentry-thermal/Valiadtion_final.ipynb', 'Jupyter'], ['Full project report · 15 pages', '../reports/reentry-thermal-model.pdf', 'PDF']]
  }
];
