// Curated from the three supplied AE353 / AE370 reports. See SITE_EDITING.md.
export const controls = [
  {
    slug: 'flying-wing-control', title: 'LQR landing controller for an unpowered flying wing', name: 'LQR landing controller for an unpowered flying wing',
    category: 'controls', type: 'Flight dynamics & control', status: 'Evaluated in simulation', art: 'plot', cardFit: 'contain',
    context: 'AE353 · Two-person team project', roleLabel: 'Team contribution',
    role: 'Controller design and evaluation reported jointly with Navid Navidzadeh',
    description: 'Designed and evaluated an LQR landing controller with a teammate using supplied aircraft dynamics. Across 4,000 randomized simulations, the controller achieved 87.3% successful landings; failure analysis examined the effect of initial attitude.',
    tags: ['LQR', 'State-space modeling', 'Python', 'SymPy'],
    lead: 'Our two-person team found a trim condition, linearized the supplied flying-wing dynamics, and tuned an LQR controller for elevon-driven landing control. We evaluated 4,000 randomized approaches and analyzed initial-attitude distributions to investigate undershoot, lateral drift, and the limits of the local controller.',
    outcome: '87.3% landing success across 4,000 simulated trials',
    image: 'flying-wing-trajectories.png', imageWidth: 1045, imageHeight: 843,
    caption: 'Simulated trajectories for 20 successful landings in green and 10 failed landings in red. The dotted outline marks the runway. Report Figure 1, pages 4–5.',
    evidenceNote: 'AE353 DP2 report by Maxwell Lutter and Navid Navidzadeh, checked against the supplied project notebooks. Dynamics and simulation infrastructure were provided by Tim Bretl, Wayne Chang, and the course staff. The report does not divide individual code authorship.',
    sections: [
      {title: 'Trim before feedback', paragraphs: ['Our team used a numerical least-squares search to establish an equilibrium for a ten-state model with two elevon inputs. Two position coordinates were excluded from the trim-state model so the aircraft could be in equilibrium while moving.', 'Jacobian linearization, a controllability check, and closed-loop eigenvalues established the basis for an LQR state-feedback controller. We iteratively tuned state and control weights to balance aircraft response against elevon motion.']},
      {title: 'Evaluate the landing, then investigate the misses', callout: '87.3% success over 4,000 randomized trials exceeded the project’s 85% landing requirement.', paragraphs: ['Evaluation began 150 m before and 15 m above the runway, with randomized initial airspeeds and small air disturbances. Successful and failed paths provided more useful evidence than a single nominal demonstration.', 'Failures included undershoot and lateral drift. Examining their initial yaw, pitch, and roll showed the limits of a controller designed around a local linear model: larger initial attitude offsets were harder to recover from.'], figure: {image: 'flying-wing-failure-attitudes.png', caption: 'Initial yaw, pitch, and roll distributions among failed landings, used to examine the controller’s operating limits. Report Figure 4, page 6.'}},
      {title: 'Implementation & attribution', paragraphs: ['The project notebooks contain the trim search, symbolic Jacobians, Riccati-equation solution for the LQR gain, a Controller class that returns right and left elevon commands, and a simulate_trials loop with landing classification and trajectory plots. These additions sit on the supplied ae353_zagi simulation interface and aircraft equations.', 'The report’s 87.3% result is supported by the saved 3,491-of-4,000 output in ZagiDemo-template.ipynb. DP2_Team33.ipynb retains a separate 1,757-of-2,000 output (87.8%), while its current call requests one trial. These are saved development states, not a new rerun. The case study uses the submitted report’s result.', 'Maxwell Lutter and Navid Navidzadeh share credit for the controller-design study. The available report does not assign particular functions to either teammate.']}
    ],
    resources: [['Full project report · 6 pages', '../reports/flying-wing-control.pdf', 'PDF']]
  },
  {
    slug: 'spacecraft-attitude', title: 'Spacecraft reaction-wheel control with star-based attitude estimation', name: 'Spacecraft reaction-wheel control with star-based attitude estimation',
    category: 'controls', type: 'Spacecraft control', status: 'Evaluated in simulation', art: 'plot', cardFit: 'contain',
    context: 'AE353 · Two-person team project', roleLabel: 'Team contribution',
    role: 'Controller and observer work reported jointly with Adrian Huang',
    description: 'Designed reaction-wheel feedback and a star-based attitude observer with a teammate. The report found observer errors below the 3.5° criterion, while the combined system achieved 64% mission success against an 80% target.',
    tags: ['LQR', 'State estimation', 'Reaction wheels', 'PyBullet'],
    lead: 'With Adrian Huang, I designed an LQR reaction-wheel controller and a dual-LQR observer to orient a spacecraft hatch for an astronaut’s return. The study evaluated attitude estimation and mission completion separately: the report found accurate estimation under noise and debris disturbances, while identifying limitations in the integrated controller’s recovery performance.',
    outcome: 'Observer criterion reported met; 64% mission success in the report’s 200-trial study',
    image: 'spacecraft-yaw-estimation.png', imageWidth: 786, imageHeight: 595,
    caption: 'True and estimated yaw during one 60-second simulation with noisy measurements and disturbances. Report Figure 1, page 6.',
    evidenceNote: 'AE353 DP3 report by Maxwell Lutter and Adrian Huang, checked against SpacecraftDemo.ipynb. Tim Bretl, Wayne Chang, and the course staff supplied the dynamics and simulation framework. Team code contributions are not individually divided in the report.',
    sections: [
      {title: 'Control from noisy measurements', paragraphs: ['The task was to keep a spacecraft hatch oriented for an astronaut’s return. Using the supplied course dynamics, our team worked with six attitude and angular-rate states, four reaction wheels in a tetrahedral arrangement, and seven observed stars producing fourteen image-plane measurements.', 'Rank-six controllability and observability checks supported LQR feedback and a dual-LQR observer. We tuned their weights and evaluated the resulting system in a Python/PyBullet simulation with noisy measurements and debris disturbances.']},
      {title: 'Two distinct evaluation results', callout: 'The report concludes that the observer met its accuracy criterion. The combined system achieved 64% mission success against an 80% target.', paragraphs: ['The observer metric was the 95th percentile of the yaw–pitch–roll error norm over 20–60 seconds. Every trial shown in the report’s observer figure falls below 3.5°. The report describes this as a comfortable accuracy margin under the tested noise and disturbances.', 'For the full mission, the report gives 64% successful entries across 200 sixty-second simulations. Its conclusion contrasts this with roughly 85% in an earlier controller-only setting, before the observer and added noise. Accurate estimation therefore did not by itself ensure a successful entry.'], figure: {image: 'spacecraft-observer-error.png', caption: 'All 25 observer trials plotted in report Figure 2 fall below the 3.5° threshold for 95th-percentile attitude-estimation error.'}},
      {title: 'Implementation & saved-run evidence', paragraphs: ['SpacecraftDemo.ipynb includes the wheel-layout model, linearization and rank checks, feedback and observer gains, and a Controller that updates its state estimate from star measurements and issues four wheel-torque commands. Trial helpers log mission outcomes and calculate estimation-error percentiles.', 'The supplied notebook saves a 25-trial run with 64% mission success, whereas the report describes 200 trials. Its observer-check call uses a 5° threshold, while the plot and report use 3.5°. The plotted values are below 3.5°, but the notebook is retained as development evidence rather than presented as a reproduction of the full reported experiment.']},
      {title: 'Engineering conclusion', paragraphs: ['The completed work combined a functioning attitude observer with reaction-wheel feedback and evaluated both against explicit criteria. The report attributes the remaining mission shortfall to the interaction of disturbances, noise, and limited control authority.', 'More systematic selection of feedback and observer weights was proposed as the next improvement. This preserves the report’s successful estimation result alongside the integrated system’s unmet mission target.']}
    ],
    resources: [['Full project report · 7 pages', '../reports/spacecraft-attitude.pdf', 'PDF']]
  },
  {
    slug: 'reentry-thermal-model', title: 'Modeling reentry heat-shield conduction and material tradeoffs', name: 'Modeling reentry heat-shield conduction and material tradeoffs',
    category: 'analysis', type: 'Computational heat transfer', status: 'Completed team study', art: 'plot', cardFit: 'contain',
    context: 'AE370 · Five-person team project', roleLabel: 'My contribution',
    role: 'Verification and implementation writing, consistency checks, result interpretation, plotting, and report editing',
    description: 'Contributed numerical verification, interpretation, and documentation for a layered heat-shield model. The team checked second-order convergence and studied how conductivity and thermal mass change surface heating and heat penetration.',
    tags: ['Finite volumes', 'Crank–Nicolson', 'Manufactured solutions', 'Verification'],
    lead: 'I checked and documented the numerical evidence for a team-developed model coupling reentry heating to conduction through a layered spherical heat shield. My work connected the finite-volume and Crank–Nicolson implementation to manufactured-solution convergence, a homogeneous-sphere analytical benchmark, plots, and report explanations.',
    outcome: 'Near-second-order convergence in space and time',
    image: 'tps-spatial-convergence.png', imageWidth: 578, imageHeight: 459,
    caption: 'Manufactured-solution spatial convergence: the reported error decreases by about a factor of four when radial grid spacing is halved. Report Figure 3, page 7.',
    evidenceNote: 'AE370 report by Jeremy Zang, Landon Lopez, Danfeng Ye, Max Lutter, and Kenny Carter. Individual contributions are documented on page 14.',
    sections: [
      {title: 'Connect trajectory, heating, and conduction', paragraphs: ['The team coupled a reduced-order reentry trajectory and Sutton–Graves surface heating to radially symmetric conduction through a layered spherical thermal-protection system.', 'Conservative finite volumes on spherical shells, harmonic interface conductivity, Crank–Nicolson time integration, and a tridiagonal solver formed the conduction model. The trajectory used a point-mass model and RK4 integration.']},
      {title: 'Check the numerical method', callout: 'Observed spatial orders: 1.987–1.999. Observed temporal orders: 1.932–1.995.', paragraphs: ['Manufactured solutions measured convergence against a known temperature field. A separate constant-flux homogeneous-sphere benchmark compared finite-volume cell averages with cell-averaged analytical values.', 'For the reported analytical test at 960 radial cells and a 0.01 s time step, the maximum discrepancy was 0.0161 K. This measures agreement in a specific numerical benchmark; it does not establish that reentry temperature predictions are physically accurate to that tolerance.'], figure: {image: 'tps-analytical-check.png', caption: 'Numerical and cell-averaged analytical temperatures for a homogeneous sphere at 10 s. The reported maximum error in this benchmark is 0.0161 K. Figure 5, page 9.'}},
      {title: 'My contribution', paragraphs: ['I wrote portions of the implementation and numerical-reliability sections, checked methods and derivations against the code and course material, helped interpret verification results and resolve inconsistencies, and contributed to plotting, report structure, and editing.', 'The report credits Danfeng Ye with implementing the conduction solver, verification suite, parameter sweeps, and run scripts. My contribution focused on checking and communicating the technical evidence.']},
      {title: 'What the material study concluded', paragraphs: ['The report identifies a tradeoff between surface and internal protection: reducing conductivity improves insulation at the back face while increasing surface temperature; increasing conductivity carries heat inward faster. Increasing volumetric heat capacity lowers temperature peaks and generally delays back-face heating.', 'The study prioritizes back-face response because the steep surface gradient is more sensitive to the numerical grid. These are conclusions from an idealized model with prescribed heating, constant material properties, and no ablation or radiative cooling. The verification tests establish numerical behavior, rather than flight qualification or a material-selection decision.']}
    ],
    resources: [['Full project report · 15 pages', '../reports/reentry-thermal-model.pdf', 'PDF'], ['Team source repository', 'https://github.com/Landon-Lopez57/AE370-Project-2', 'GitHub']]
  }
];
