// Source: the seven-page DP4 report, its contribution appendix, and the saved final notebook.
export const drone = {
  slug: 'drone-obstacle-course',
  title: 'Navigating a drone obstacle course with an observer and collision-avoidance guidance',
  name: 'Navigating a drone obstacle course with an observer and collision-avoidance guidance',
  category: 'controls', type: 'Autonomous flight control', status: 'Evaluated in PyBullet simulation',
  art: 'plot', cardFit: 'contain', context: 'AE353 DP4 · Maxwell Lutter & Landon Lopez', roleLabel: 'My contribution',
  role: 'Primary developer of the final drone code; collaborative modeling, gain selection, navigation strategy, trial automation, and report work',
  description: 'Developed the final drone code with Landon Lopez, connecting noisy-sensor state estimates and LQR feedback to ring-crossing guidance and obstacle repulsion. Automated repeated trials to assess completion, speed, and failure behavior.',
  tags: ['LQR', 'State estimation', 'Collision avoidance', 'PyBullet', 'Python'],
  lead: 'The challenge was to turn a hover controller into a drone that could navigate a three-dimensional course of rings and obstacles using noisy sensor measurements. With Landon Lopez, I combined state estimation, feedback, and course-level guidance, then automated repeated simulations to test completion and speed. I was the primary developer of the final drone code; the resulting design completed 95 of 100 trials and met both project requirements.',
  outcome: '95/100 course completions; 73.35 s mean among successful runs',
  codeLink: ['View controller, observer & trial code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/drone'],
  image: 'drone-completion-times.png', imageWidth: 490, imageHeight: 390,
  caption: 'Successful completion times from the saved notebook. All 95 successful runs finished below 80 seconds, with a mean of 73.35 seconds. The other five trials did not complete the course.',
  evidenceNote: 'DP4: Control Design for a Drone Race, by Maxwell Lutter and Landon Lopez. The contribution appendix identifies Maxwell as the primary developer of the final drone code. The saved notebook retains the reported result text. Dynamics, sensor equations, simulator, and course assets were supplied AE353 material.',
  sections: [
    {title: 'Start with a controller that can hold hover', paragraphs: ['The team linearized the quadrotor dynamics around stationary, level hover. The twelve-state model includes position, attitude, linear velocity, and angular rate, with three body-torque commands and total thrust as its four inputs.', 'The sensors report noisy positions at the front and back rotors. Linearizing this measurement model and checking full-rank controllability and observability supported an LQR controller and a dual-LQR observer. The observer reconstructs the state used by feedback, so the navigation logic can operate on estimated position rather than an unavailable exact state.']},
    {title: 'Turn ring locations into a flyable reference', paragraphs: ['Simply jumping the target from one ring center to the next would ask the local hover controller to make abrupt corrections. The design instead advances a moving reference toward the next checkpoint. The retained implementation uses near and far waypoints on opposite sides of a ring to guide a crossing, with a visit state that determines which waypoint is active.', 'Reference motion is capped, and local proximity checks reduce speed near obstacles. Distance-dependent repulsion steers the reference away from obstacles, other drones, and the nearest ring edge. Separate gains for ring geometry and other objects allow the approach behavior to be adjusted without changing the stabilizing feedback design.', 'The design philosophy favored consistent completion over the fastest possible run. This guidance layer was the key bridge between a linear model around hover and a nonlinear navigation task with collisions and checkpoint geometry.']},
    {title: 'Test the requirements across randomized courses', callout: '95 of 100 trials completed the course; successful runs averaged 73.35 s.', paragraphs: ['The trial workflow initialized the simulator repeatedly, logged states and estimates, and recorded the simulator’s completion flag and finish time. Randomized starting conditions and course geometry tested whether the design worked beyond one nominal demonstration.', 'The requirements were at least 80% course completion and a mean completion time below 80 seconds among successful runs. Both were met. The 95 successful times ranged from 68.36 to 79.12 seconds; the 73.35-second mean excludes the five failures.', 'Tracking-error and position-estimation-error distributions helped separate reference-following behavior from observer behavior. Most recorded estimation errors were near zero, while larger departures appeared around sharp maneuvers and failure cases.'], figure: {image: 'drone-estimation-errors.png', imageWidth: 989, imageHeight: 390, caption: 'Saved position-error distributions pooled over simulation time steps: reference-tracking error at left and state-estimation error at right. These are position-error magnitudes in meters.'}},
    {title: 'Use the five failures to identify the next improvements', paragraphs: ['The report locates all five failed trajectories near the obstacle region. Sharp changes in direction and divergence between true and estimated position suggested collision-related disturbances and difficulty stabilizing during or after close approaches.', 'The team proposed greater ring-edge clearance, further tuning of controller and observer weights, and smoother transitions in the desired trajectory. Faster operation was also a possible follow-on because the design had prioritized consistency. These are proposed improvements; the documented result remains the 100-trial simulation study.'], figure: {image: 'drone-failed-trajectories.png', imageWidth: 690, imageHeight: 380, caption: 'Overhead view of the five failed trials. Red paths show actual and estimated position; black outlines show checkpoint rings. Retaining these cases explains the remaining completion gap.'}},
    {title: 'My contribution: integrate the design and produce evidence', paragraphs: ['The report credits my work on linearizing the dynamics and sensor model, selecting control and observer gains, making navigation decisions, automating repeated-trial data collection, generating figures, and revising the report. It identifies me as the primary developer of the final drone code. Landon contributed controller implementation, obstacle avoidance, methods writing, and analysis and conclusions.', 'The linked notebook exposes the path from symbolic modeling and Riccati-equation gains to the Controller class, ring-visit logic, state-estimate updates, bounded commands, trial automation, and failure plots. This shows experience integrating modeling, estimation, guidance, and evaluation into one working system, with measured acceptance criteria and remaining limitations. The testing was in PyBullet; it does not establish physical-flight performance.']}
  ],
  resources: [
    ['Controller, observer, trial code & contribution notes', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae353/drone', 'GitHub code'],
    ['Archived design and evaluation notebook', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/drone/DP4%20Drone%28Lutter%29.ipynb', 'Jupyter'],
    ['Readable notebook code', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/drone/drone_design_and_trials.py', 'Python'],
    ['Related standalone controller version', 'https://github.com/m-lutter/portfolio/blob/main/project-code/ae353/drone/mlutter2.py', 'Python'],
    ['Full project report · 7 pages', '../reports/drone-obstacle-course.pdf', 'PDF']
  ]
};
