// Based on the supplied FieldPlan v21 and FieldMark2 compression-slider sources.
// Both applications were developed for, and are copyrighted by, Talman Consultants, LLC.
export const fieldTools = [
  {
    slug: 'fieldplan', title: 'FieldPlan: turn work lists into maps and driving routes',
    name: 'FieldPlan: turn work lists into maps and driving routes', artLabel: 'FieldPlan',
    category: 'software', type: 'Field planning software', status: 'Public web application',
    art: 'fieldplan', image: 'fieldplan-route-map.png', imageWidth: 1280, imageHeight: 720, cardFit: 'contain',
    caption: 'Live FieldPlan preview with 40 randomly placed synthetic Chicago work locations: 30 red and 10 yellow. All three work areas and routes are displayed, starting and finishing at Talman HQ in Westmont. Lines connect the ordered stops. Captured September 11, 2026. Map: © OpenStreetMap contributors.',
    context: 'Professional work · Talman Consultants, LLC',
    description: 'Turned mixed work lists and map files into a repeatable field-planning workflow. The Python app reconciles locations and readiness, divides assignments, and uses road-network distances to order routes and export field maps.',
    tags: ['Python', 'Streamlit', 'OR-Tools', 'Geospatial data'],
    lead: 'I developed FieldPlan for Talman Consultants, LLC to turn scattered work lists and existing maps into usable field assignments. The engineering work connects input cleanup and work-readiness rules to geographic partitioning, road-network routing, and exports that crews can take into the field.',
    role: 'Workflow design, Python development & iteration',
    outcome: 'Public Streamlit application for field planning',
    evidenceNote: 'Based on the maintained v21 Python source, synthetic checks, and live-app screenshots captured with synthetic work records on September 11, 2026.',
    sections: [
      { title: 'Goal: make the work list actionable', paragraphs: ['A route is only useful if its stops represent the work that actually needs doing. FieldPlan accepts raw Excel workbooks, coordinate CSV files, and existing KML/KMZ maps together so users can assemble one project without first converting every source into the same format.', 'I built a workflow that identifies usable columns, uses supplied coordinates or geocodes location text, retains map context where possible, and exposes skipped records and conflicts for review. The output is a common set of labeled locations that can feed both assignments and routing.'] },
      { title: 'Resolve ambiguity before optimizing', paragraphs: ['Repeated labels can refer to the same site or to different places. Nearby repeated Excel locations can be merged, including sites appearing in both HMA and PCC lists. Distant points sharing a label remain separate and appear in a coordinate-conflict report, avoiding a silent merge of distinct jobs.', 'Work completion and photo readiness are separate filters. Explicit photo status takes precedence; when Thermo work is complete and the photo field is blank, the site becomes yellow and is included only if the user enables that category. Merged records retain the more conservative status. These rules make the map reflect workflow state rather than merely show every uploaded row.'], figure: { image: 'fieldplan-project-setup.png', imageWidth: 1280, imageHeight: 720, caption: 'A synthetic HMA/PCC workbook becomes 40 locations and three depot-balanced work areas. The fictional coordinates were randomly placed within Chicago’s public community-area boundaries.' } },
      { title: 'Use geography for assignments and roads for travel', paragraphs: ['Users can retain existing assignment polygons or generate new regions. The depot-balanced method creates contiguous sectors around Talman HQ using an approximate route-workload measure; a simpler rectangular method offers an alternative. These are planning suggestions that users can inspect, not guaranteed optimal territories.', 'Straight-line proximity does not capture road travel. OSRM supplies road-network distance and time matrices, and Google OR-Tools uses them to find stop orders under the chosen start, finish, and trip constraints. Users can route a group, all locations, or groups in a batch, with fixed trip counts or mileage and drive-time limits.', 'Ordered CSVs, route-ready KMZs, and an interactive preview carry the plan into the next workflow. Preview lines connect the ordered stops; they do not depict turn-by-turn road geometry.'], figure: { image: 'fieldplan-route-results.png', imageWidth: 1280, imageHeight: 720, caption: 'Ordered stops and trip summaries for all three synthetic groups, each returning to Talman HQ. Travel figures are estimates for this example, not measured field performance.' } },
      { title: 'Outcome and verification', callout: 'A public Streamlit application connecting data cleanup, readiness rules, assignments, and route exports.', paragraphs: ['Repository checks exercise status precedence, inclusion filters, duplicate handling, complete route visits, and KMZ output using synthetic work lists and a supplied distance matrix. The displayed live-app example contains 40 fictional Chicago locations, with 30 red and 10 yellow records, partitioned into three areas.', 'The project demonstrates translating an operational workflow into explicit data rules, combining geospatial formats, integrating external services with a routing solver, and checking that exported records preserve the intended jobs. Routing remains heuristic and depends on geocoding and road-service availability; no measured time or mileage savings are claimed.'] },
      { title: 'Ownership', paragraphs: ['Developed by Maxwell Lutter for Talman Consultants, LLC. Copyright © 2026 Talman Consultants, LLC. All rights reserved.'] }
    ],
    resources: [['Open FieldPlan', 'https://fieldplan.streamlit.app/', 'Live application']]
  },
  {
    slug: 'fieldmark2', title: 'FieldMark2: turn GPS photos into field records and maps',
    name: 'FieldMark2: turn GPS photos into field records and maps', artLabel: 'FieldMark2',
    category: 'software', type: 'Field records software', status: 'Python desktop application',
    image: 'fieldmark-record-workflow.svg', imageWidth: 1200, imageHeight: 560, cardFit: 'contain',
    caption: 'Processing workflow drawn from the maintained FieldMark2 source. Photos and CSV data become structure-based records, with manual review for missing information and separate compression rules for exported copies.',
    context: 'Professional work · Talman Consultants, LLC',
    description: 'Built a desktop pipeline that groups GPS-tagged photos and CSV records by field structure. It reconciles nearby records, preserves detail-sensitive images, and exports Excel contact sheets and photo-linked KMZ maps.',
    tags: ['Python', 'Tkinter', 'Pillow', 'Excel / KMZ'],
    lead: 'I developed FieldMark2 for Talman Consultants, LLC to convert folders of field photographs into structure-based records. The challenge was to associate several images with the right pole or underground structure, combine them with existing CSV data, and produce useful maps without unnecessarily large image archives.',
    role: 'Workflow design, Python development & iteration',
    outcome: 'Excel fielding records and KMZ maps from photo folders',
    evidenceNote: 'Based on the supplied compression-slider application and synthetic processing/export checks.',
    sections: [
      { title: 'Goal: organize evidence around the structure', paragraphs: ['A folder of photos is not yet a fielding record: several photographs may describe one structure, and existing CSV records may already hold its location and notes. FieldMark2 scans JPEGs and CSVs, extracts GPS metadata, and uses folder names to distinguish poles, handholes, manholes, and related support images.', 'The output is organized by structure, with Excel rows and photo contact sheets for review and KMZ placemarks containing the associated photographs. For applicable underground records with neither conduit information nor notes, a review dialog collects the missing details before export.'] },
      { title: 'Match records without hiding uncertainty', paragraphs: ['The processor combines proximity with compatible structure types rather than merging every nearby image. Separate rules associate OCalc and pole-support photographs with poles and marker photographs with handholes. This encodes the relationship between a photograph and the record it supports.', 'Phone GPS and inconsistent folders can still produce ambiguity. Missing-GPS images are counted as skipped, and unassociated support images are reported as unmatched. Proximity is a practical grouping heuristic, so those counts help users decide what needs manual review; it does not establish survey accuracy.'] },
      { title: 'Trade archive size against useful detail', paragraphs: ['Embedding full-resolution photos can make KMZs cumbersome. I exposed five compression levels so the user can control the copies included in the map. The default caps ordinary images at 1024 × 768 pixels with JPEG quality 65, preserving aspect ratio without enlarging small images.', 'OCalc photographs bypass recompression and retain their original bytes, preserving the detail needed for their downstream use. Original input photographs are retained; the size tradeoff applies to exported copies. This exception keeps a convenient global compression setting from damaging a specific class of evidence.'] },
      { title: 'Outcome and technical evidence', callout: 'A Python/Tkinter tool that turns photo folders into Excel fielding records and photo-linked KMZ maps.', paragraphs: ['The repository includes installation guidance, a Windows packaging script, and explicitly synthetic sample inputs. Processing checks cover GPS metadata, structure grouping, Excel rows, KMZ image references, compression dimensions, and byte-preserved OCalc images.', 'This work demonstrates file-format integration, geospatial matching, image handling, and verification of exported artifacts. The checks establish behavior for the sample pipeline; real-device formats, manual review interactions, and KMZ viewer behavior still require deployment-specific checking.'] },
      { title: 'Ownership', paragraphs: ['Developed by Maxwell Lutter for Talman Consultants, LLC. Copyright © 2026 Talman Consultants, LLC. All rights reserved.'] }
    ],
    resources: [
      ['Source and setup instructions', 'https://github.com/m-lutter/FieldMark2', 'GitHub'],
      ['Processing and export checks', 'https://github.com/m-lutter/FieldMark2/tree/main/tests', 'Tests']
    ]
  }
];
