// Source: The Other Side final presentation, slides 1–18, reviewed September 2026.
export const otherSide = {
  slug: 'the-other-side', title: 'The Other Side: discrete-logic LED game', name: 'The Other Side: discrete-logic LED game',
  category: 'hardware', type: 'Digital systems integration', status: 'Built & demonstrated', art: 'photo',
  context: 'Team project · Maxwell Lutter & Carlos Selvi', roleLabel: 'Team & contribution',
  role: 'Co-authored with Carlos Selvi; digital-logic game design and implementation',
  description: 'Co-built a playable 4 × 4 LED game from discrete digital logic. Bounded state machines, independent clocks, and an active-low display interface turned simulated movement and collision rules into working breadboard hardware.',
  tags: ['Finite state machines', '555 timers', 'Logisim', 'Breadboarding'],
  lead: 'With Carlos Selvi, I took an obstacle-avoidance game from gameplay rules and logic simulation to a working breadboard. The challenge was to make movement, timing, display polarity, and game termination behave as one system using discrete logic and a 4 × 4 RGB LED display.',
  outcome: 'Physical game with bounded movement, win/loss freeze, and reset',
  image: 'other-side-hardware.jpg', imageWidth: 1536, imageHeight: 2048, cardFit: 'cover',
  caption: 'The team’s completed breadboard game and 4 × 4 RGB LED display, from slide 2 of the final presentation.',
  evidenceNote: 'Based on the 18-slide final presentation by Maxwell Lutter and Carlos Selvi. Team results are described collectively; the deck does not assign individual subsystem ownership.',
  sections: [
    {title: 'Goal: implement the rules in hardware', paragraphs: ['The player moves a blue LED across a 4 × 4 display while red obstacles cross its path. Reaching the top row must register a win; occupying an obstacle position must register a loss. Both events must hold the final display until reset.', 'These rules became separate input, state, timing, display, and termination subsystems. Two two-bit state machines track horizontal and vertical position; a decoder maps the four position bits to an LED. Obstacle counters feed the same logical space so combinational logic can detect a collision.'], figure: {image: 'other-side-block-diagram.png', caption: 'Original system block diagram, slide 4: the interfaces that connect input, state, timing, display, and termination logic.'}},
    {title: 'Design decisions at the subsystem interfaces', paragraphs: ['A shift-register approach could move the player beyond the display. We replaced it with bounded state machines whose transitions hold position at an edge. Updating the two axes independently also permits diagonal movement without adding a separate diagonal state.', 'Sampling directional buttons on a 555 clock’s rising edge limits movement speed. Separate player and obstacle clocks allow different rates, but clocked input has a usability cost: a short button press between edges can be missed. The presentation identifies this as a limitation of the implemented control scheme.', 'The simulated logic also had to match the physical display. Active-low decoder outputs needed inversion to drive the RGB LED board. Collision and win logic then controlled the timers’ supply path through a tri-state buffer so termination would freeze the displayed state.']},
    {title: 'Build up from a model to the breadboard', paragraphs: ['An early gameplay prototype established the intended behavior and useful clock speeds. Logisim let us check the complete logic with simplified clocks and displays, while CircuitVerse and Tinkercad supported individual circuit experiments.', 'The breadboard then required the logical interfaces to work electrically: button inputs, state outputs, display decoding, and timer control had to agree. The final presentation records the schematic, state assignments, transition logic, and physical game. Maxwell Lutter and Carlos Selvi share credit; the deck does not divide ownership of individual subsystems.']},
    {title: 'Outcome and engineering evidence', callout: 'A built game with directional and diagonal movement, boundary handling, win/loss indication, freeze, and reset.', paragraphs: ['The team reported completing the core behavior in physical hardware. An independently timed second obstacle row and adjustable difficulty remained proposed extensions; those features were not part of the documented final build.', 'This project provides concrete evidence of translating behavior into state transitions, designing timing and logic interfaces, and carrying a simulated design through physical integration. The clocked-button limitation also shows where the working circuit could improve as a user interface.']}
  ],
  gallery: [{image: 'other-side-schematic.png', caption: 'Original full-circuit schematic, slide 5. Open the image to inspect the components and connections.'}],
  resources: [
    ['Final presentation · 18 slides', 'https://docs.google.com/presentation/d/1G4IhLfdZ-8-l1hMifEOL0JBLiHnG6s6grLI5HEp1oHA/edit', 'Google Slides'],
    ['Frogger Lite · earlier simulation', 'frogger-fsm.html', 'Case study'],
    ['Original simulation & design notes', 'https://github.com/m-lutter/portfolio/tree/main/Circuit6%3A%20Frogger%20Lite', 'GitHub']
  ]
};
