// Sources: supplied AE461 laboratory reports, read from their LaTeX archives.
// Lab 6 assigns individual work. The other reports credit results to the team.
const team = 'AE461 · Four-person laboratory team';
const authors = 'Reports by A. Alptekin, E. Bennett, M. Lutter, and S. Konakanchi, as credited in the supplied documents.';

export const structures = [
  {
    slug: 'photoelastic-stress', title: 'Measuring notch stresses with photoelasticity and FEA', name: 'Measuring notch stresses with photoelasticity and FEA',
    category: 'structures', type: 'Experimental stress analysis', status: 'Completed laboratory study', art: 'plot', cardFit: 'contain',
    context: team, roleLabel: 'Team contribution', role: 'Coauthored the experimental stress-analysis report',
    description: 'Used visible fringe patterns to investigate how U- and V-notches concentrate bending stress. Comparing measurements, analytical estimates, and Abaqus output exposed a geometry limit in the V-notch approximation.',
    tags: ['Photoelasticity', 'Four-point bending', 'Stress concentration', 'Abaqus'],
    lead: 'A notch changes where a beam carries stress, even when the applied load is unchanged. Our team used photoelastic beams in four-point bending to make that redistribution visible, then connected the fringe patterns to stress calculations and finite-element results. The central engineering question was whether a convenient analytical estimate remained suitable for each notch geometry.',
    outcome: 'Visualized notch stress concentrations and identified a limit in the V-notch approximation',
    image: 'photoelastic-u-notch.png', imageWidth: 887, imageHeight: 322,
    caption: 'U-notched beam under 100 N applied load. The report’s annotations identify fringe orders and measurement locations near the notch.',
    evidenceNote: `${authors} Lab 2: Measurement of Stress using Photoelasticity. The source does not divide individual tasks; measurements, calculations, and FEA results are credited to the team.`,
    sections: [
      {title: 'Make an internal stress field measurable', paragraphs: ['The team compared an unnotched beam with U- and V-notched specimens in a screw-driven four-point-bending fixture. A load cell measured applied force, and a CCD camera recorded the specimens inside a monochromatic dark-field polariscope.', 'The unnotched beam provided a calibration case: its known bending-stress distribution was used to estimate the material fringe constant. Applying that calibration to the notched beams connected fringe order and measured position to the local stress distribution.'], figure: {image: 'photoelastic-loading-setup.png', caption: 'Four-point-loading arrangement photographed in the Lab 2 report, with the inner and outer loading-point spacings annotated.'}},
      {title: 'Check whether the model fits the geometry', paragraphs: ['The U-notch analytical estimate gave a maximum stress of 15.09 MPa, close to the 14.67 MPa compressive-stress magnitude reported by Abaqus. The V-notch comparison was substantially less consistent: the extrapolated estimate was 36.04 MPa, while Abaqus gave 19.95 MPa.', 'The report identifies a specific limitation in the V-notch calculation. Its notch-depth-to-radius ratio was 25.4, beyond the correlation’s stated range of 2–20. It therefore examined both a value bounded at 20 and an extrapolated estimate. The disagreement supports checking an approximation’s applicability before relying on its numerical result.'], figure: {image: 'photoelastic-u-notch-fea.png', caption: 'U-notch bending-stress contour included in the team report’s Abaqus comparison.'}},
      {title: 'Outcome and engineering judgment', paragraphs: ['The fringe patterns showed stress becoming concentrated near the notch edges, rather than remaining distributed as in the unnotched beam. Additional specimens, including a horseshoe shape, supported qualitative identification of peak-stress locations even when the internal loads were not known.', 'As a report coauthor, I contributed to a study that connects physical observations, calibration, analytical assumptions, and FEA evidence. The important result is the ability to explain both agreement and disagreement; the report does not establish individual ownership of the measurements or Abaqus work.']}
    ],
    resources: [['Four-point-loading setup', '../assets/photoelastic-loading-setup.png', 'Report photograph'], ['U-notch fringe image', '../assets/photoelastic-u-notch.png', 'Report figure'], ['U-notch FEA comparison', '../assets/photoelastic-u-notch-fea.png', 'Report figure']]
  },
  {
    slug: 'rod-buckling', title: 'Testing how supports, material, and eccentricity affect rod buckling', name: 'Testing how supports, material, and eccentricity affect rod buckling',
    category: 'structures', type: 'Structural stability testing', status: 'Completed laboratory study', art: 'plot', cardFit: 'contain',
    context: team, roleLabel: 'Team contribution', role: 'Coauthored the buckling-test and Euler-theory comparison',
    description: 'Compared compression tests with Euler buckling predictions while changing supports, material, and load eccentricity. The fixed–fixed test fell well below its ideal prediction, making restraint quality a central part of the analysis.',
    tags: ['Euler buckling', 'Force–deflection', 'Boundary conditions', 'Experimental mechanics'],
    lead: 'Ideal column theory assumes supports and loading that a real fixture can only approximate. Our team tested slender rods in compression to separate the effects of end restraint, material stiffness, and eccentric loading. The force–deflection measurements showed where Euler theory described the trend and where fixture imperfections changed the result.',
    outcome: 'Measured stiffness trends supported Euler theory; the fixed–fixed test exposed restraint sensitivity',
    image: 'rod-buckling-apparatus.png', imageWidth: 352, imageHeight: 502,
    caption: 'Labeled buckling-test apparatus diagram included in the Lab 4 report: load spindle, adjustable crossbar, specimen restraints, and force-measuring device.',
    evidenceNote: `${authors} Lab 4: Buckling of Slender Rods. The report provides joint results without an individual task breakdown. The apparatus illustration is reproduced from the report, not presented as an original design.`,
    sections: [
      {title: 'Separate three causes of instability', paragraphs: ['A load nut applied axial compression through interchangeable pinned or clamped specimen holders. The frame measured force, while a lateral gauge tracked rod deflection. Recording the full force–deflection response made it possible to distinguish a load plateau from progressive bending.', 'The support study used similar steel specimens so that the mounting was the main variable. A second comparison held geometry and pinned supports constant while changing material; a third introduced eccentric loading. The analysis used the corresponding effective lengths and weak-axis second moments of area in Euler’s critical-load relation.']},
      {title: 'Investigate the fixed–fixed discrepancy', callout: 'Pinned–pinned: 500 N measured / 548.56 N predicted. Fixed–pinned: 950 / 1116.75 N. Fixed–fixed: 710 / 2194.26 N.', paragraphs: ['The first two arrangements followed the expected increase with stronger restraint. The fixed–fixed specimen did not: it buckled below the fixed–pinned result and far below the ideal fixed–fixed prediction.', 'The report attributes this departure to imperfect clamping, alignment, initial curvature, and possible load eccentricity. Those are proposed explanations, rather than separately measured causes. The result shows why nominal support labels alone are insufficient to establish an experimental boundary condition.']},
      {title: 'Read the response beyond a single critical load', paragraphs: ['Equal-geometry pinned specimens carried 850 N in aluminum, 1100 N in brass, and 1225 N in copper. The increase with the listed Young’s moduli supported the predicted stiffness trend, without demonstrating exact linear agreement.', 'Greater load eccentricity produced more initial bending and a more gradual loss of stiffness, with the most eccentric specimen carrying the lowest maximum load. This changed the observable response from a sharp idealized buckling event toward a continuous compression-and-bending process.'], figure: {image: 'rod-buckling-force-deflection.png', caption: 'S2 force–deflection measurements from the report, showing a load plateau near 850 N.'}},
      {title: 'Outcome and engineering judgment', paragraphs: ['The team concluded that Euler theory explains the principal influence of stiffness and restraint while real supports and loading imperfections materially affect stability. The fixed–fixed exception is part of that conclusion.', 'I coauthored this team report. The study provides evidence of comparing measured behavior with an ideal model, controlling comparison variables, and discussing an anomalous result without treating it as a successful match. Individual tests and calculations remain credited to the team.']}
    ],
    resources: [['Buckling-test apparatus', '../assets/rod-buckling-apparatus.png', 'Report diagram'], ['S2 force–deflection curve', '../assets/rod-buckling-force-deflection.png', 'Report figure']]
  },
  {
    slug: 'beam-modal-testing', title: 'Identifying cantilever modes with shaker and impact-hammer tests', name: 'Identifying cantilever modes with shaker and impact-hammer tests',
    category: 'structures', type: 'Experimental modal analysis', status: 'Completed laboratory study', art: 'plot', cardFit: 'contain',
    context: team, roleLabel: 'Team contribution', role: 'Coauthored the vibration-testing and modal-analysis report',
    description: 'Connected visible beam motion to frequency-domain measurements, then reconstructed five mode shapes from 17 impact locations. Manual resonance selections agreed with EDM Modal results within 0.4% for every measured mode.',
    tags: ['Modal analysis', 'Impact hammer', 'Frequency response', 'EDM Modal'],
    lead: 'A frequency-response peak becomes useful when it can be connected to a physical vibration mode. Our team first observed an aluminum cantilever under shaker excitation, then used a roving impact hammer and a tip accelerometer on a steel cantilever to identify five resonances and reconstruct their mode shapes. Comparing manual FRF interpretation with EDM Modal provided a consistency check on the identification process.',
    outcome: 'Identified five impact-test modes; manual and EDM frequencies differed by less than 0.4%',
    image: 'beam-shaker-mode.png', imageWidth: 537, imageHeight: 382,
    caption: 'Second mode of the aluminum beam observed during the shaker/stroboscope test. The report marks its nodes; the separate steel-beam impact-test results appear below.',
    evidenceNote: `${authors} Lab 5: Structural Dynamics Experiment. The source does not assign individual measurement or analysis tasks. Shaker and impact results concern two different beam setups.`,
    sections: [
      {title: 'Use motion to interpret the measurements', paragraphs: ['The shaker test applied harmonic base excitation to an aluminum cantilever. A stroboscope made the motion appear stationary so that the team could observe nodes and the increasing complexity of successive bending modes.', 'For the impact test, a steel cantilever was fixed to a heavy support block. Keeping the tip accelerometer in one location while moving the hammer through 17 excitation locations gave a spatial set of input–response measurements without relocating the response sensor.']},
      {title: 'Identify resonances without misreading the FRF', paragraphs: ['The signal analyzer and EDM Modal produced complex frequency response functions (FRFs). The team identified resonances using magnitude peaks and imaginary-component extrema, with real-component and phase behavior as supporting evidence.', 'Two interpretation details mattered: an imaginary response could be a positive peak or a negative trough depending on mode and impact location, and phase jumps between +180° and −180° represented wrapping rather than a data error. Considering multiple components and locations reduced dependence on a single plotted feature.']},
      {title: 'Reconstruct and cross-check five modes', callout: 'Impact-test resonances: 24.0, 154.5, 428.2, 840.4, and 1383.4 Hz.', paragraphs: ['The imaginary amplitudes at each resonance were extracted across the 17 locations and normalized to estimate the mode shapes. The experimental shapes followed the analytical and EDM trends most closely at lower modes; higher modes showed more visible differences.', 'Manual FRF frequencies differed from EDM Modal by 0.29%, 0.39%, 0.20%, 0.25%, and 0.22%. This checks two ways of interpreting the measured response. The shaker portion had a separate 2.41% average difference from its prelab frequency estimates; it is not the same comparison.'], figure: {image: 'beam-modal-shapes.png', caption: 'Five normalized mode-shape comparisons from the impact test: manual FRF extraction, analytical shapes, and EDM Modal across 17 excitation locations.'}},
      {title: 'Outcome and engineering judgment', paragraphs: ['The experiment met its objective of identifying natural frequencies and mode shapes. The report discusses finite frequency resolution, damping, measurement noise, and the effect of the tip accelerometer’s mass: the measured system was the instrumented beam, not an ideal unloaded beam.', 'I am a coauthor of the team report. Its measurement-to-interpretation sequence provides evidence of experimental dynamics and physically grounded signal analysis; the source does not establish which member collected or processed particular FRFs.']}
    ],
    resources: [['Observed shaker mode', '../assets/beam-shaker-mode.png', 'Report photograph'], ['Five-mode comparison', '../assets/beam-modal-shapes.png', 'Report figure']]
  },
  {
    slug: 'composite-tensile-testing', title: 'Comparing composite tensile behavior with extensometer and DIC strain', name: 'Comparing composite tensile behavior with extensometer and DIC strain',
    category: 'structures', type: 'Composite materials testing', status: 'Completed laboratory study', art: 'plot', cardFit: 'contain',
    context: team, roleLabel: 'My contribution', role: 'Stress–strain comparisons, specific properties, apparatus and uncertainty documentation, and manufacturing-quality discussion',
    description: 'Compared contact and optical strain measurements in graphite/epoxy tensile tests at 0°, ±45°, and 90°. My analysis connected orientation-dependent performance with measurement uncertainty and the limits of ideal laminate predictions.',
    tags: ['Composite materials', 'Tensile testing', 'Digital image correlation', 'Experimental uncertainty'],
    lead: 'The objective was to connect how graphite/epoxy coupons were manufactured and oriented with how they actually carried tensile load. I prepared the stress–strain comparisons and weight-normalized properties, and documented the apparatus, manufacturing history, and uncertainty. The tests established strong directional behavior, while substantial differences from theoretical stiffness and failure loads made measurement quality and model assumptions central to the story.',
    outcome: '0° coupon reached 807.7 MPa; directional trends were clear, but ideal predictions did not match quantitatively',
    codeLink: ['View recovered tensile-analysis code', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae461/composite-tensile'],
    image: 'composite-tensile-apparatus.svg', imageWidth: 1200, imageHeight: 760,
    caption: 'Apparatus schematic adapted from the Lab 6 report: Instron loading and extensometer measurements alongside camera-based digital image correlation. This is a diagram of the test arrangement, not a photograph.',
    evidenceNote: `${authors} Lab 6: Mechanical Property Testing of Composite Materials. Maxwell’s responsibilities are explicitly listed in “Contribution of Individual Group Members.” The recovered Python appendix is credited to the team.`,
    sections: [
      {title: 'Compare three orientations and two strain measurements', paragraphs: ['The team manufactured and tested coupons with fibers aligned with the load, transverse to it, and at ±45°. An Instron load frame pulled the tabbed coupons to failure. Measured force, width, and thickness gave engineering stress; a 25.4 mm extensometer supplied axial strain during initial loading.', 'A camera also recorded the speckled coupon surface at 10 images per second for Vic-2D digital image correlation (DIC). The optical method measured strain in a selected region, while the extensometer averaged strain over its gage length. Using both made the strain measurement itself part of the comparison.']},
      {title: 'Turn two data streams into comparable curves', paragraphs: ['My assigned stress–strain section compared both methods for all three orientations. The recovered team Python script reads Instron specimen metadata, converts force and area to stress in MPa, and aligns the DIC image sequence with the Instron record using a linear time mapping. It plots the response up to peak load and filters obvious failed-correlation outliers.', 'That synchronization is approximate. Near fracture, cracks and rapid local deformation reduced optical correlation quality; the extensometer was removed before final failure to protect it. Those practical limits matter when interpreting the end of the curves. The published code preserves the analysis for inspection, but the complete input time histories were not recovered, so no fresh processing run is claimed.'], figure: {image: 'composite-stress-strain-0.png', caption: 'The report’s 0° stress–strain comparison. It places contact and optical strain measurements against the same engineering stress.'}},
      {title: 'Make the weight comparison explicit', paragraphs: ['I also calculated specific modulus and specific strength by dividing the measured properties by an approximate cured density of 1530 kg/m³. For the 0° coupon, the report gives 44.86 MN·m/kg specific modulus and 527.9 kN·m/kg specific strength. These are normalized estimates using the stated density assumption, not separately measured material allowables.', 'My apparatus and uncertainty sections identified thickness variation, specimen alignment, grip or tab effects, optical region selection, and image quality as important influences. My earlier manufacturing-history sections covered quality, lay-up temperature and humidity, and the cure cycle. These establish plausible sources of variation; they do not isolate the cause of each discrepancy.']},
      {title: 'Establish the trend and explain the limits', callout: '0° coupon: 68.64 GPa extensometer modulus and 807.7 MPa ultimate tensile strength.', paragraphs: ['The 0° specimen was stiffest and strongest, the 90° specimen was weakest in tension, and the ±45° specimen reached the largest strain before failure. The 0° DIC modulus was 84.53 GPa: closer to the theoretical 156.78 GPa than the extensometer value, but still substantially lower.', 'The team’s failure-load comparison showed 48.27 kN measured against 115.34 kN predicted at 0°, and 1.74 against 4.18 kN at 90°. The ±45° specimen instead carried 7.40 kN against a 4.49 kN prediction. The report describes the failure model as conservative for that tested shear-dominated case, rather than generally accurate for every orientation.'], figure: {image: 'composite-stress-strain-45.png', caption: 'The ±45° response shows greater strain and nonlinear behavior associated with shear-dominated loading.'}},
      {title: 'My contribution and the engineering evidence', paragraphs: ['The report specifically credits me with stress–strain curves, specific-property calculations, apparatus and uncertainty documentation, and manufacturing-quality and cure-history discussion. It assigns primary modulus and strength extraction to E. Bennett, off-axis properties and failure-load predictions to A. Alptekin, and laminate constants and modulus comparisons to S. Konakanchi.', 'My contribution demonstrates translating test records into meaningful comparisons while documenting how the measurements were made and what assumptions bound the conclusion. The result is an experimentally supported account of directional composite behavior and its uncertainty, rather than a qualification claim or proof that ideal predictions match manufactured coupons.'], figure: {image: 'composite-stress-strain-90.png', caption: 'The 90° stress–strain response documents the much weaker transverse tensile behavior.'}}
    ],
    resources: [['Recovered team analysis code and input notes', 'https://github.com/m-lutter/portfolio/tree/main/project-code/ae461/composite-tensile', 'GitHub code'], ['Tensile-test apparatus schematic', '../assets/composite-tensile-apparatus.svg', 'Report-based diagram'], ['0° stress–strain comparison', '../assets/composite-stress-strain-0.png', 'Report figure'], ['±45° stress–strain comparison', '../assets/composite-stress-strain-45.png', 'Report figure'], ['90° stress–strain comparison', '../assets/composite-stress-strain-90.png', 'Report figure']]
  }
];
